cv_url: /assets/Jaemin_Jo_CV.pdf
github_url: https://github.com/e-
scholar_url: https://scholar.google.com/citations?user=fw7ft64AAAAJ
my_name: Jaemin Jo
profile: /images/Me.png
blog_url: http://jaeminjo.tumblr.com
